require("tree-sitter-manager").setup({
	parser_dir = vim.fn.stdpath("data") .. "/site/parser",
	query_dir = vim.fn.stdpath("data") .. "/site/queries",
	--assume_installed = {} maybe c and cpp if errors occur,
	ensure_installed = {
        "lua",
        "python",
        "cpp",
        "asm",
        "c",
        "json",
        "rust",
        "typescript",
        "javascript",
        "go",
		"java",
		"haskell",
		"ocaml",
		"c_sharp",
		"kotlin"
	},
	auto_install = false,
	noauto_install = {},
	highlight = true,
	nohighlight = {},
	languages = {},
	nerdfont = true,
	border = "rounded",
	min_width = 78,
	min_height = 40,
})
